[project]
name = "greeter"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aws-cdk-lib>=2.232.1",
    "constructs>=10.4.3",
]

[dependency-groups]
dev = [
    "ipython>=9.8.0",
    "jupyterlab>=4.5.0",
    "pytest>=9.0.2",
    "ruff>=0.14.8",
]

[tool.ruff]
line-length = 120